#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Extension Build and Publish
on:
  push:
    paths:
      - '**/extension.json'
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-20.04

    steps:
    - name: Clone source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and publish changed sidecar definitions
      run: |
        ./.ci/extension_build_publish.sh build-publish HEAD^1 HEAD

    - name: List release files
      id: release-files
      run: |
        echo ::set-output name=files_to_release::"$(cat release_files)"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.release-files.outputs.files_to_release }}
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
